# Alternatively you can use [build.dependencies]
# the syntax is the same as Cargo.toml's; you don't need to specify path or git
#[target.thumbv6m-none-eabi]
# the flags below have zero effect
#rustflags = [
#    "-C", "link-arg=-nostartfiles",
#    "-C", "link-arg=-lnosys",
#    "-C", "link-arg=-nostdlib",
#]

[target.thumbv7em-none-eabi.dependencies]
alloc = {}

# Build with xargo build --target thumbv7em-none-eabi --verbose
