# Alternatively you can use [build.dependencies]
# the syntax is the same as Cargo.toml's; you don't need to specify path or git

# Bare Cortex-M0, M0+, M1
[target.thumbv6m-none-eabi.dependencies]
alloc = {}

# Bare Cortex-M3
[target.thumbv7m-none-eabi.dependencies]
alloc = {}

# Bare Cortex-M4, M7
[target.thumbv7em-none-eabi.dependencies]
alloc = {}

# Bare Cortex-M4F, M7F, FPU, hardfloat
[target.thumbv7em-none-eabihf.dependencies]
alloc = {}

# Simulation targets are below
[target.x86_64-unknown-linux-gnu.dependencies]
alloc = {}
alloc_system = {}

[target.i686-apple-darwin.dependencies]
alloc = {}
alloc_system = {}

[target.i686-unknown-linux-gnu.dependencies]
alloc = {}
alloc_system = {}

