[package]
name = "rust_alloc_chibios"
version = "0.1.0"
authors = ["Michal Podhradsky <mpodhradsky@galois.com>"]
edition = "2018"

#[lib]
#name = "rust_alloc_chibios"
#path = "src/lib.rs"
#crate-type = ["staticlib"]

[dependencies]

[features]
"arch32" = []
"arch16" = []
default = ["arch32"]
